api:
  host_url: "https://www.soliscloud.com:13333"
  content_type: "application/json"
  verb: "POST"

db:
  influx_url: "https://i.emitsolar.my"
  influx_org: "emitsolar"
  influx_bucket: "inverter_api_test"
